In [3]:
#DECLARAÇÃO DE BIBLIOTECAS

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_20newsgroups
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.naive_bayes import BernoulliNB
from sklearn import metrics
from sklearn.metrics import accuracy_score, roc_curve, auc

In [4]:
#INPUT DE DADOS

#Features
x_train = np.array(['Chinese Beijing Chinese','Chinese Chinese Shanghai','Chinese Macao','Tokyo Japan Chinese']) 
 
#Labels
y_train = np.array(['china','china','china','not china']) 

#Teste
x_test = np.array(['Chinese Chinese Chinese Tokyo Japan']) 

In [19]:
#MODELOS
#CRIAR O MODELO MULTINOMIAL

vetor_multi = CountVectorizer(binary=False) #cria a matriz que conta o numero de vezes que cada termo aparece no texto

X_train_dtm_multinomial = vetor_multi.fit_transform(x_train)

tipo_modelo1 = MultinomialNB() #define o classificador

multinomial = make_pipeline(vetor_multi, tipo_modelo1) #cria modelo

#CRIAR O MODELO BERNOULLI

vetor_bernoulli = CountVectorizer(binary=True) #cria a matriz que mostra se a palavra aparece ou nao na mensagem

X_train_dtm_bernoulli = vetor_bernoulli.fit_transform(x_train)

nb = BernoulliNB(binarize=None)

In [20]:
#TREINOS

multinomial.fit(x_train, y_train) #treino do modelo multinomial

nb.fit(X_train_dtm, y_train) #treino do modelo bernoulli

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [21]:
#TESTES

y_pred_multinomial = multinomial.predict(x_test) #teste de validacao multinomial

X_test_dtm_bernoulli = vetor_bernoulli.transform(x_test)

y_pred_bernoulli = nb.predict(X_test_dtm_bernoulli) #test de validacao bernoulli

In [22]:
#RESULTADO DOS TESTES

print('Label Multinomial: ',y_pred_multinomial)
print('Label Bernoulli: ', y_pred_bernoulli)

Label Multinomial:  ['china']
Label Bernoulli:  ['not china']


In [24]:
#PRINT DADOS

print('Nomes dos atributos: ', vetor_multi.get_feature_names())
print('Matriz de contagem Multinomial: ')
print(X_train_dtm_multinomial.toarray())
print('Matriz de Contagem Bernoulli: ')
print(X_train_dtm_bernoulli.toarray()) 

Nomes dos atributos:  ['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
Matriz de contagem Multinomial: 
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]
Matriz de Contagem Bernoulli: 
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]
